# Generated by Django 5.0.2 on 2024-02-25 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='img',
        ),
    ]
