# Generated by Django 5.0.2 on 2024-03-05 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_order_product_order_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_Details',
            new_name='Order_Detail',
        ),
    ]
