# Generated by Django 5.0.2 on 2024-03-05 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_order_customer_alter_order_detail_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='createdTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=None),
        ),
    ]
