# Generated by Django 5.0.2 on 2024-03-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_order_createdtime_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_detail',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='order_detail',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
