# Generated by Django 5.0.2 on 2024-03-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_order_id_order_detail_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
